apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  annotations:
    getambassador.io/rolloutId: 3bb61188-27ae-48dc-bdec-fcdaf1d9d5bb
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: web-app
    app.kubernetes.io/part-of: emojivoto
  name: web-app
  namespace: emojivoto
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  strategy:
    canary:
      canaryService: web-app-canary
      stableService: web-app
      steps:
      - setWeight: 30
      - pause:
          duration: 40
      - setWeight: 60
      - pause:
          duration: 40
      - setWeight: 90
      - pause:
          duration: 40
      trafficRouting:
        ambassador:
          mappings:
          - web-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web-app
        revision: 2021-09-23.01
    spec:
      containers:
      - env:
        - name: WEB_PORT
          value: "80"
        - name: INDEX_BUNDLE
          value: dist/index_bundle.js
        image: danielbryantuk/emojivoto-web-app:v11.5
        imagePullPolicy: Always
        name: web-app
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            cpu: 100m
      serviceAccountName: web-app
status:
  blueGreen: {}
  canary: {}
